export const createTablePatient: string = `
DROP TABLE IF EXISTS patients;
CREATE TABLE IF NOT EXISTS patients (
  PatientId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Gender TEXT NOT NULL,
  DateOfBirth TEXT NOT NULL,
  MobileNo INTEGER NOT NULL,
  Address TEXT NOT NULL,
  Image BLOB NULL,
  CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);`;
